# Generated by Django 4.1 on 2023-01-06 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(blank=True, max_length=5, null=True, verbose_name="Teacher's office")),
                ('scientific_degree', models.CharField(choices=[('DS', 'Doctor of Sciences'), ('CS', 'Candidate of Sciences')], max_length=2, verbose_name='Scientific degree')),
                ('academic_status', models.CharField(choices=[('RO', 'Senior Research Officer'), ('DC', 'Docent'), ('PR', 'Professor')], max_length=2, verbose_name='Academic status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
