# Generated by Django 4.1 on 2023-01-08 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_faculty_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, max_length=30, null=True, verbose_name='Specialty')),
                ('educational_program', models.CharField(blank=True, max_length=30, null=True, verbose_name='Educational program')),
                ('educational_level', models.CharField(blank=True, choices=[('Б', 'Бакалаврат'), ('М', 'Магістратура'), ('Д', 'Докторантура')], max_length=30, null=True, verbose_name='Educational level')),
                ('group', models.CharField(blank=True, max_length=6, null=True, verbose_name='Group')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Entry date')),
                ('education_form', models.CharField(blank=True, choices=[('Д', 'Денна'), ('З', 'Заочна')], max_length=10, null=True, verbose_name='Education form')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
