# Generated by Django 4.1 on 2023-01-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='education_form',
            field=models.CharField(blank=True, choices=[('Денна', 'Денна'), ('Заочна', 'Заочна')], max_length=10, null=True, verbose_name='Education form'),
        ),
        migrations.AlterField(
            model_name='student',
            name='educational_level',
            field=models.CharField(blank=True, choices=[('Бакалавр', 'Бакалаврат'), ('Магістр', 'Магістратура'), ('Докторант', 'Докторантура')], max_length=30, null=True, verbose_name='Educational level'),
        ),
    ]
