# Generated by Django 4.1 on 2023-01-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Бали'),
        ),
    ]
