# Generated by Django 4.1.5 on 2023-06-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Дисципліна загальної підготовки', 'Дисципліна загальної підготовки'), ('Дисципліна професійної підготовки', 'Дисципліна професійної підготовки'), ('Вибіркова дисципліна', 'Вибіркова дисципліна')], max_length=33, null=True, verbose_name='Тип дисципліни'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='academic_status',
            field=models.CharField(choices=[('Ст. науковий дослідник', 'Ст. науковий дослідник'), ('Доцент', 'Доцент'), ('Професор', 'Професор')], max_length=22, verbose_name='Вчене звання'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='scientific_degree',
            field=models.CharField(choices=[('Доктор наук', 'Доктор наук'), ('Кандидат наук', 'Кандидат наук')], max_length=13, verbose_name='Науковий ступінь'),
        ),
    ]
