# Generated by Django 4.1.5 on 2023-06-06 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_student_department_student_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='educational_program',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_educational_program', to='main.department'),
        ),
    ]
